### ISSUE TITLE
verify carbon pools parameters

### ISSUE THREAD

**Issue by davemfish** [natcap/urban-online-workflow#103]
Some of the storage values don't seem to make sense, in terms of how some LULC classes compare to others. For example, more above-ground carbon is store in "Developed" areas than in forests?

And more is stored above-ground in High Intensity Development than in Developed Open Space or Shrub/Scrub? Maybe accounting for urban tree planting? Though I would think the highest intensity development category would represent something like a parking lot.

@chrisnootenboom can you give us a sanity-check here let us know if any changes are needed? 

I'm referencing the values in https://github.com/chrisnootenboom/urban-workflow/blob/master/naturban/data/parameters/urban_carbon_nlcd_bioregions.csv

**Comment by chrisnootenboom** [comment]
This is a carbon table built off of global estimates of carbon stock in cities. The aboveground carbon includes estimates of urban trees (which we have not updated with the new tree canopy data--this will be reduced in areas with little to no tree canopy) as well as biomass carbon stored in things like furniture and wooden building materials.

This table was primarily intended to contrast these biomass estimates with **annual emissions** and **embedded emissions**, which derive from our work in Guangzhou. However, the scenarios we worked with in San Antonio ended up being exclusively on **Vacant Land** and **Developed, Open Space**, so we effectively ignored both the higher aboveground carbon in more developed areas AND any changes in embedded/annual emissions, since neither of those LULC categories nor the food forest scenarios had any relevant emissions.

All that to say: those numbers are hard to explain without contrasting them to the embedded emissions in building materials, pavement, etc.  If it comes up in the meeting tomorrow I am happy to field the question.

Looking forward, I'll need to submit a PEP for the updates to the carbon model...

**Comment by davemfish** [comment]
Thanks, @chrisnootenboom , that's very helpful context. I never would have thought about wooden buildings as a carbon pool. 

>Looking forward, I'll need to submit a PEP for the updates to the carbon model...

Well we just need updated biophysical tables, right? That doesn't require a PEP.

We could update the single global table we have now, if that makes sense. Or we could update one bioregion at a time. Right now we're storing a copy of the tables from your other repo in this repo, so if we're making changes that should only be applied to the web-app and not your other workflow, then we can change the tables here. Or if the changes _should_ be applied to your other workflow as well, then we have some scripts here in `scripts/prepare_invest_data` that can pull those tables from your repo.
