### ISSUE TITLE
/pattern/ patterns table needs to reference thumbnails

### ISSUE THREAD

**Issue by davemfish** [natcap/urban-online-workflow#44]
The database of patterns needs to include thumbnails of the patterns, since that's one of the most useful ways for a user to browse the existing patterns.

**Comment by phargogh** [comment]
Working on the thumbnail creation process in `feature/44-create-thumbnail` on my fork

**Comment by phargogh** [comment]
@davemfish @emlys Here's the current state of what the thumbnail function produces ... any feedback?

The whole image here is the thumbnail ... the cyan box in the middle is the selected pattern area.  Internally we buffer that selected pattern area by a bit in order to get the final LULC, which is what you see here in the thumbnail, that whole LULC.

<img width="286" alt="Screen Shot 2022-08-12 at 3 08 21 PM" src="https://user-images.githubusercontent.com/4583897/184450999-f33e670d-6607-4f64-857b-c83758d803b9.png">

**Comment by davemfish** [comment]
Whoops, sorry I didn't notice this issue sooner. I think the user will want to see a thumbnail that matches just what was inside the box they used to make the selection (or at least close to that, if you want to include the pixels on the edge of the box). Thanks @phargogh

**Comment by phargogh** [comment]
OK great!  I've updated this to have just the clipped area plus about 1 pixel boundary to get a little bit of the context:

![thumbnail_pattern](https://user-images.githubusercontent.com/4583897/185482190-ac0b7f22-d520-4237-b679-0a2a998eb865.png)

@dcdenu4 do we have a thumbnail request jobtype yet?

**Comment by dcdenu4** [comment]
@phargogh , see my proposed endpoint solution in your PR #54 !

**Comment by phargogh** [comment]
Thanks @dcdenu4 !  I've pushed an update to #54 that adds the endpoint stuff there.  Let me know if there's anything that'd be helpful to talk about there!

**Comment by dcdenu4** [comment]
Done!
