### ISSUE TITLE
Add a legend for the LULC map

### ISSUE THREAD

**Issue by emlys** [natcap/urban-online-workflow#45]
We received feedback that a legend for the LULC map would be helpful. This could go in a few places -
- in the paint options dropdown, show a color swatch 🟩 next to each option label
- display a (toggleable) legend in the corner of the map (maybe impractical with a larger set of LULC classes)
- show LULC class on hover?

We also got a question about the definition of the NLCD classes and differences between them. Some of the class names (e.g. "emergent herbaceous") are kind of ecology jargon. We may need to provide simplified user-facing names and/or guidance on what each class means.

**Comment by davemfish** [comment]
On hold until we update the LULC with the latest version that will probably have many more categories

**Comment by davemfish** [comment]
We're not updating the LULC layer in the immediate future, so we should go ahead and add a legend. In my opinion it should be subtle. It should only display when the LULC raster is displayed. 

> in the paint options dropdown, show a color swatch 🟩 next to each option label
I think this a good idea on its own, but not sure it satisfies the requirement of this issue because people might not find it when they need it. 

> display a (toggleable) legend in the corner of the map (maybe impractical with a larger set of LULC classes)
This is probably a reliable option. Maybe we can be creative about where it displays, it doesn't necessarily have to be over the map.

> show LULC class on hover?
I like this best as I generally think labels are better than legends. But this option surely requires the most engineering.

**Comment by dcdenu4** [comment]
Dave and I talked about this some more and think it's worth trying the approach of displaying the LULC Class on hover over. That location could move with the mouse or static somewhere on the map, like lower middle... Maybe with an option to hide?

**Comment by davemfish** [comment]
Done in #100
