### ISSUE TITLE
`/parcel_fill/` always fills with 0s

### ISSUE THREAD

**Issue by davemfish** [natcap/urban-online-workflow#63]
It seems no matter what integer is sent as the LULC code, the resulting raster is all 0s.

**Comment by dcdenu4** [comment]
When testing `parcel_fill` I noticed an error occurring on the worker that could be part of the problem:

```
urban-online-workflow-worker-1    | ERROR 1: ICreateFeature: Mismatched geometry type
urban-online-workflow-worker-1    | Warning 1: /opt/appdata/NLCD_2016.tif: This file used to have optimizations in its layout, but those have been, at least partly, invalidated by later changes
urban-online-workflow-worker-1    | ERROR 1: ICreateFeature: Mismatched geometry type
urban-online-workflow-worker-1    | ERROR 1: ICreateFeature: Mismatched geometry type
```

This appears to be caused by how the endpoint API is constructing the WKT from multiple parcel polygons. Currently the WKT is being constructed using shapely MultiPolygon. I just tested using `shapely.ops.unary_union` to dissolve the polygons into a single Polygon. Sending that WKT to the worker seemed okay.

**Comment by phargogh** [comment]
Both of the issues mentioned here should now be resolved as of f5c046d.

The `/parcel_fill` always filling with 0 was a mismatch between the NLCD's actual dtype, nodata and what the code was using for these.  This has now been fixed.

The `ERROR 1: ICreateFeature: Mismatched geometry type` has been resolved by changing the vector geometry types from the default of `ogr.wkbPolygon` to `ogr.wkbMultiPolygon` and the errors no longer appear.

@davemfish @dcdenu4 could you confirm that this is resolved for you?

**Comment by davemfish** [comment]
Thanks team, this is working great, now!

**Comment by dcdenu4** [comment]
Thanks!
