### ISSUE TITLE
Urban Cooling: AOI vector

### ISSUE THREAD

**Issue by davemfish** [natcap/urban-online-workflow#88]
For now we're using a simple box of the same extent as the LULC raster as the AOI, since it is a required input. I believe the AOI is only used to aggregate/summarize results, so we might want something more meaningful like administrative boundaries (census tracts, etc). Although the choice of the right boundary might depend on the geographic extent of the scenario. Or maybe it should be selected by the user?

Also, since I think it's only being used for aggregations, if the model doesn't do exactly what we need, we could do this step as a custom post-processing routine.

**Comment by dcdenu4** [comment]
I think from our recent conversation that using the simple box approach is fine for now since the results we'll be grabbing is just a difference of sums across scenarios. However, for future valuation metrics the AOI / aggregation bounds will matter more as averages and other metrics will be skewed by having a larger AOI than needed.

**Comment by davemfish** [comment]
Done in #101
